# Generated by Django 4.0.6 on 2022-07-16 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0002_uuidtaggeditem_alter_code_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='product',
            new_name='projects',
        ),
    ]
